export const dispatchActioTypes = {
  LOAD_DATA: "LOAD_DATA",
	LOADING_DATA: "LOADING_DATA",
  SET_ERROR:"SET_ERROR",
  CREATE_PLAYLIST_WITH_VIDEO:"CREATE_PLAYLIST_WITH_VIDEO",
  UPDATE_PLAYLIST:"UPDATE_PLAYLIST",
  UPDATE_LIKED_VIDEO:"UPDATE_LIKED_VIDEO",
  UPDATE_WATCH_LATER:"UPDATE_WATCH_LATER",
  UPDATE_HISTORY:"UPDATE_HISTORY",
  CATEGORY_FILTER:"CATEGORY_FILTER",
  ALL_CATEGORY:"ALL_CATEGORY",
}