export const dispatchActioTypes = {
  LOAD_DATA: "LOAD_DATA",
	LOADING_DATA: "LOADING_DATA",
  SET_ERROR:"SET_ERROR",
  CREATE_PLAYLIST_WITH_VIDEO:"CREATE_PLAYLIST_WITH_VIDEO",
  UPDATE_PLAYLIST:"UPDATE_PLAYLIST"
}